export const IMG_URL =
  "https://www.shutterstock.com/image-illustration/no-picture-available-placeholder-thumbnail-600nw-2179364083.jpg";
export const fruit_descriptions = [
  "Apples are crisp and sweet with a variety of colors.",
  "Bananas are a versatile, yellow fruit with a mild flavor.",
  "Oranges are citrus fruits known for their juicy, tangy taste.",
  "Grapes come in clusters and can be red, green, or purple.",
  "Strawberries are small, red, and sweet berries.",
  "Watermelons are large, refreshing fruits with sweet, pink flesh.",
  "Mangoes are tropical fruits with a sweet and juicy taste.",
  "Pineapples have a spiky exterior and sweet, tropical flavor.",
  "Peaches are fuzzy fruits with juicy, fragrant flesh.",
  "Kiwis are small, brown fruits with vibrant green flesh.",
  "Blueberries are small, round berries known for their antioxidants.",
  "Pears are sweet and come in various shapes and colors.",
  "Cherries are small, red or purple fruits with a sweet and tart taste.",
  "Plums are smooth-skinned fruits with sweet and juicy flesh.",
  "Raspberries are small, red berries with a slightly tart flavor.",
  "Cantaloupes have orange, juicy flesh and a sweet aroma.",
  "Apricots are small, golden fruits with a sweet and velvety texture.",
  "Pomegranates have a tough outer rind and juicy, ruby-red seeds.",
  "Coconuts have a hard outer shell and sweet, coconut water inside.",
  "Lemons are sour citrus fruits commonly used for their juice.",
  "Limes are green, tangy fruits often used in cooking and drinks.",
  "Avocados have a creamy texture and a mild, nutty taste.",
  "Papayas have orange, tropical flesh with a sweet flavor.",
  "Grapefruits are large citrus fruits with a tangy and slightly bitter taste.",
  "Nectarines are smooth-skinned fruits similar to peaches but without fuzz.",
  "Blackberries are dark purple berries with a sweet and tart flavor.",
  "Rambutans are hairy fruits with sweet, translucent flesh.",
  "Dragon Fruit, or pitaya, has a vibrant pink skin and mildly sweet taste.",
  "Passion Fruit has a tough outer rind and aromatic, juicy seeds.",
  "Guavas are tropical fruits with a fragrant aroma and sweet taste.",
  "Figs are unique fruits with a chewy texture and sweet flavor.",
  "Lychees are small, red fruits with translucent, juicy flesh.",
  "Persimmons are orange fruits with a sweet and honey-like taste.",
  "Cranberries are small, red berries often used in sauces and juices.",
  "Mandarin Oranges are small, citrus fruits with a sweet flavor.",
  "Tangerines are similar to mandarins, known for their easy-to-peel skin.",
  "Kumquats are tiny citrus fruits that can be eaten whole.",
  "Dates are sweet, brown fruits with a chewy texture.",
  "Star Fruit, or carambola, has a unique star-shaped cross-section.",
  "Honeydew Melons have pale green flesh and a sweet, mild flavor.",
  "Jackfruits are large fruits with yellow, fibrous flesh and a sweet taste.",
  "Raspberries are small, red berries with a slightly tart flavor.",
  "Clementines are small, easy-to-peel citrus fruits.",
  "Cucumbers, although commonly considered vegetables, are technically fruits.",
  "Persimmons are orange fruits with a sweet and honey-like taste.",
  "Cherimoyas have a green, scaly skin and sweet, custard-like flesh.",
  "Mangoes are tropical fruits with a sweet and juicy taste.",
  "Melons refer to various large, juicy fruits like watermelon and cantaloupe.",
];
export const fruits = [
  "Apple",
  "Banana",
  "Orange",
  "Grapes",
  "Strawberry",
  "Watermelon",
  "Mango",
  "Pineapple",
  "Peach",
  "Kiwi",
  "Blueberry",
  "Pear",
  "Cherry",
  "Plum",
  "Raspberry",
  "Cantaloupe",
  "Apricot",
  "Pomegranate",
  "Coconut",
  "Lemon",
  "Lime",
  "Avocado",
  "Papaya",
  "Grapefruit",
  "Nectarine",
  "Blackberry",
  "Rambutan",
  "Dragon Fruit",
  "Passion Fruit",
  "Guava",
  "Fig",
  "Lychee",
  "Persimmon",
  "Cranberry",
  "Mandarin Orange",
  "Tangerine",
  "Kumquat",
  "Date",
  "Star Fruit",
  "Honeydew Melon",
  "Jackfruit",
  "Raspberry",
  "Clementine",
  "Cucumber",
  "Persimmon",
  "Cherimoya",
  "Mango",
  "Melon",
];

export const fnames = ["John", "Emma", "Michael", "Olivia", "Daniel", "Sophia"];

export const lnames = ["Doe", "Smith", "Johnson", "Williams", "Brown", "Davis"];

export const orderDetails = [
  {
    orderid: 1,
    productid: 2,
    quantity: 2,
  },
  {
    orderid: 1,
    productid: 4,
    quantity: 3,
  },
  {
    orderid: 1,
    productid: 12,
    quantity: 5,
  },
  {
    orderid: 2,
    productid: 2,
    quantity: 1,
  },
  {
    orderid: 2,
    productid: 20,
    quantity: 3,
  },
  {
    orderid: 3,
    productid: 1,
    quantity: 5,
  },
  {
    orderid: 3,
    productid: 18,
    quantity: 3,
  },
  {
    orderid: 4,
    productid: 15,
    quantity: 1,
  },
];
